# Joystick Inputs für Twist-Message (2 DOF)
inputs:
  linear:
    x: undefined
  angular:
    z: undefined

# Controller-Layouts <-- arg in StatusToTurtleTwist.launch
layouts:
  linear:
    x1: axis_left_y
    x2: axis_left_y
    x3: axis_r2 - axis_l2
  angular:
    z1: axis_l2 - axis_r2
    z2: axis_right_x
    z3: axis_left_x

# Skalierung der Geschwindigkeit [%]
scales:
  linear:
    x: 0.5
  angular:
    z: 1.0

distance: 
  min: 0.12
  max: 3.5
  critical: 0.8
  
# Haptische Outputs
rumble:
  # Vibration bei Bewegung
  velocity:
    # Stärke der Vibration [%]
    linear: 0.2
    angular: 0.1
  # haptische Objekterkennung [m]
  distance:
    min: 0.12
    max: 0.8
